#!/usr/bin/env python3
"""Generate GymBuiltinExerciseEntries.kt from structured exercise data."""

from __future__ import annotations

import json
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "app/src/main/java/com/deepak/flow/core/gym/GymBuiltinExerciseEntries.kt"

# (id_suffix, name, primary, secondary[], equipment, aliases[])
# id becomes builtin:{id_suffix}
EXERCISES: list[tuple] = []

def add(id_suffix, name, primary, secondary, equipment, aliases=()):
    EXERCISES.append((id_suffix, name, primary, list(secondary), equipment, list(aliases)))

# --- CHEST ---
for e in [
    ("barbell_bench_press", "Barbell Bench Press", "CHEST", [], "BARBELL", ["BB Bench Press", "BB Bench", "Barbell Bench", "Bench Press Barbell"]),
    ("incline_barbell_bench_press", "Incline Barbell Bench Press", "CHEST", ["SHOULDERS"], "BARBELL", ["Incline BB Bench", "Incline Barbell Bench"]),
    ("decline_barbell_bench_press", "Decline Barbell Bench Press", "CHEST", ["TRICEPS"], "BARBELL", ["Decline BB Bench", "Decline Barbell Bench"]),
    ("close_grip_barbell_bench_press", "Close Grip Barbell Bench Press", "CHEST", ["TRICEPS"], "BARBELL", ["Close Grip Bench", "Close Grip BB Bench"]),
    ("dumbbell_chest_press", "Dumbbell Chest Press", "CHEST", ["TRICEPS"], "DUMBBELL", ["DB Chest Press", "Chest Press DB", "Dumbbell Bench Press", "DB Bench Press"]),
    ("incline_dumbbell_press", "Incline Dumbbell Press", "CHEST", ["SHOULDERS"], "DUMBBELL", ["Incline DB Press", "Incline DB Bench"]),
    ("decline_dumbbell_press", "Decline Dumbbell Press", "CHEST", ["TRICEPS"], "DUMBBELL", ["Decline DB Press", "Decline DB Bench"]),
    ("neutral_grip_dumbbell_press", "Neutral Grip Dumbbell Press", "CHEST", ["TRICEPS"], "DUMBBELL", ["Neutral DB Press"]),
    ("machine_chest_press", "Machine Chest Press", "CHEST", ["TRICEPS"], "MACHINE", ["Chest Press Machine", "Machine Press"]),
    ("incline_machine_chest_press", "Incline Machine Chest Press", "CHEST", ["SHOULDERS"], "MACHINE", ["Incline Machine Press"]),
    ("smith_machine_bench_press", "Smith Machine Bench Press", "CHEST", ["TRICEPS"], "SMITH_MACHINE", ["Smith Bench Press"]),
    ("smith_machine_incline_press", "Smith Machine Incline Press", "CHEST", ["SHOULDERS"], "SMITH_MACHINE", ["Smith Incline Press"]),
    ("cable_chest_press", "Cable Chest Press", "CHEST", ["TRICEPS"], "CABLE", ["Standing Cable Chest Press"]),
    ("cable_fly", "Cable Fly", "CHEST", [], "CABLE", ["Cable Flye", "Cable Chest Fly"]),
    ("low_cable_fly", "Low Cable Fly", "CHEST", [], "CABLE", ["Low to High Cable Fly"]),
    ("high_cable_fly", "High Cable Fly", "CHEST", [], "CABLE", ["High to Low Cable Fly"]),
    ("pec_deck", "Pec Deck", "CHEST", [], "MACHINE", ["Pec Deck Fly", "Machine Fly"]),
    ("dumbbell_fly", "Dumbbell Fly", "CHEST", [], "DUMBBELL", ["DB Fly", "Dumbbell Chest Fly"]),
    ("incline_dumbbell_fly", "Incline Dumbbell Fly", "CHEST", ["SHOULDERS"], "DUMBBELL", ["Incline DB Fly"]),
    ("cable_crossover", "Cable Crossover", "CHEST", [], "CABLE", ["Cable Cross Over"]),
    ("push_up", "Push Up", "CHEST", ["TRICEPS", "SHOULDERS"], "BODYWEIGHT", ["Push-Up", "Pushup", "Push Ups"]),
    ("incline_push_up", "Incline Push Up", "CHEST", ["TRICEPS"], "BODYWEIGHT", ["Incline Push-Up"]),
    ("decline_push_up", "Decline Push Up", "CHEST", ["SHOULDERS"], "BODYWEIGHT", ["Decline Push-Up"]),
    ("diamond_push_up", "Diamond Push Up", "CHEST", ["TRICEPS"], "BODYWEIGHT", ["Diamond Push-Up"]),
    ("wide_grip_push_up", "Wide Grip Push Up", "CHEST", [], "BODYWEIGHT", ["Wide Push Up"]),
    ("chest_dip", "Chest Dip", "CHEST", ["TRICEPS", "SHOULDERS"], "BODYWEIGHT", ["Weighted Chest Dip"]),
    ("floor_press", "Floor Press", "CHEST", ["TRICEPS"], "BARBELL", ["Barbell Floor Press", "BB Floor Press"]),
    ("dumbbell_floor_press", "Dumbbell Floor Press", "CHEST", ["TRICEPS"], "DUMBBELL", ["DB Floor Press"]),
    ("landmine_press", "Landmine Press", "CHEST", ["SHOULDERS"], "LANDMINE", ["Single Arm Landmine Press"]),
    ("svend_press", "Svend Press", "CHEST", [], "OTHER", ["Plate Squeeze Press"]),
    ("resistance_band_chest_press", "Resistance Band Chest Press", "CHEST", ["TRICEPS"], "RESISTANCE_BAND", ["Band Chest Press"]),
    ("resistance_band_fly", "Resistance Band Fly", "CHEST", [], "RESISTANCE_BAND", ["Band Fly"]),
    ("kettlebell_floor_press", "Kettlebell Floor Press", "CHEST", ["TRICEPS"], "KETTLEBELL", ["KB Floor Press"]),
    ("single_arm_dumbbell_press", "Single Arm Dumbbell Press", "CHEST", ["CORE"], "DUMBBELL", ["One Arm DB Press"]),
    ("guillotine_press", "Guillotine Press", "CHEST", ["SHOULDERS"], "BARBELL", ["Neck Press"]),
]:
    add(*e)

# --- BACK ---
for e in [
    ("pull_up", "Pull Up", "BACK", ["BICEPS"], "BODYWEIGHT", ["Pull-Up", "Pullup", "Pull Ups"]),
    ("chin_up", "Chin Up", "BACK", ["BICEPS"], "BODYWEIGHT", ["Chin-Up", "Chinup"]),
    ("neutral_grip_pull_up", "Neutral Grip Pull Up", "BACK", ["BICEPS"], "BODYWEIGHT", ["Neutral Pull Up"]),
    ("weighted_pull_up", "Weighted Pull Up", "BACK", ["BICEPS"], "BODYWEIGHT", ["Weighted Pull-Up"]),
    ("lat_pulldown", "Lat Pulldown", "BACK", ["BICEPS"], "CABLE", ["Lat Pull Down", "Lat Pull-Down", "Lat Pulldowns", "Pulldown"]),
    ("close_grip_lat_pulldown", "Close Grip Lat Pulldown", "BACK", ["BICEPS"], "CABLE", ["Close Grip Pulldown"]),
    ("wide_grip_lat_pulldown", "Wide Grip Lat Pulldown", "BACK", ["BICEPS"], "CABLE", ["Wide Grip Pulldown"]),
    ("reverse_grip_lat_pulldown", "Reverse Grip Lat Pulldown", "BACK", ["BICEPS"], "CABLE", ["Underhand Lat Pulldown"]),
    ("single_arm_lat_pulldown", "Single Arm Lat Pulldown", "BACK", ["BICEPS"], "CABLE", ["One Arm Lat Pulldown"]),
    ("straight_arm_pulldown", "Straight Arm Pulldown", "BACK", ["TRICEPS"], "CABLE", ["Straight Arm Pushdown"]),
    ("barbell_row", "Barbell Row", "BACK", ["BICEPS"], "BARBELL", ["BB Row", "Bent Over Barbell Row", "Bent-Over Row"]),
    ("pendlay_row", "Pendlay Row", "BACK", ["BICEPS"], "BARBELL", ["Dead Stop Row"]),
    ("yates_row", "Yates Row", "BACK", ["BICEPS"], "BARBELL", ["Underhand Barbell Row"]),
    ("dumbbell_row", "Dumbbell Row", "BACK", ["BICEPS"], "DUMBBELL", ["DB Row", "One Arm Dumbbell Row", "Single Arm Row"]),
    ("chest_supported_dumbbell_row", "Chest Supported Dumbbell Row", "BACK", ["BICEPS"], "DUMBBELL", ["Incline DB Row"]),
    ("meadows_row", "Meadows Row", "BACK", ["BICEPS"], "BARBELL", ["Landmine Row"]),
    ("t_bar_row", "T Bar Row", "BACK", ["BICEPS"], "BARBELL", ["T-Bar Row", "Landmine T Bar Row"]),
    ("seated_cable_row", "Seated Cable Row", "BACK", ["BICEPS"], "CABLE", ["Cable Row", "Seated Row"]),
    ("chest_supported_row", "Chest Supported Row", "BACK", ["BICEPS"], "MACHINE", ["Machine Row", "Chest Supported Machine Row"]),
    ("machine_row", "Machine Row", "BACK", ["BICEPS"], "MACHINE", ["Plate Loaded Row"]),
    ("inverted_row", "Inverted Row", "BACK", ["BICEPS"], "BODYWEIGHT", ["Bodyweight Row", "Australian Pull Up"]),
    ("cable_pullover", "Cable Pullover", "BACK", ["CHEST"], "CABLE", ["Straight Arm Pullover"]),
    ("dumbbell_pullover", "Dumbbell Pullover", "BACK", ["CHEST"], "DUMBBELL", ["DB Pullover"]),
    ("machine_pullover", "Machine Pullover", "BACK", ["CHEST"], "MACHINE", ["Nautilus Pullover"]),
    ("face_pull", "Face Pull", "BACK", ["SHOULDERS", "TRAPS"], "CABLE", ["Cable Face Pull"]),
    ("reverse_fly", "Reverse Fly", "BACK", ["SHOULDERS"], "DUMBBELL", ["Rear Delt Fly", "Bent Over Reverse Fly"]),
    ("cable_reverse_fly", "Cable Reverse Fly", "BACK", ["SHOULDERS"], "CABLE", ["Cable Rear Delt Fly"]),
    ("machine_reverse_fly", "Machine Reverse Fly", "BACK", ["SHOULDERS"], "MACHINE", ["Reverse Pec Deck"]),
    ("rack_pull", "Rack Pull", "BACK", ["GLUTES", "HAMSTRINGS"], "BARBELL", ["Partial Deadlift"]),
    ("conventional_deadlift", "Conventional Deadlift", "BACK", ["GLUTES", "HAMSTRINGS"], "BARBELL", ["Deadlift", "Barbell Deadlift", "BB Deadlift"]),
    ("sumo_deadlift", "Sumo Deadlift", "BACK", ["GLUTES", "QUADS"], "BARBELL", ["Sumo DL"]),
    ("trap_bar_deadlift", "Trap Bar Deadlift", "BACK", ["GLUTES", "QUADS"], "TRAP_BAR", ["Hex Bar Deadlift"]),
    ("romanian_deadlift", "Romanian Deadlift", "HAMSTRINGS", ["GLUTES", "BACK"], "BARBELL", ["RDL", "Romanian DL", "Romanian Deadlifts"]),
    ("stiff_leg_deadlift", "Stiff Leg Deadlift", "HAMSTRINGS", ["GLUTES"], "BARBELL", ["SLDL", "Stiff-Leg Deadlift", "Stiff Leg DL"]),
    ("single_leg_romanian_deadlift", "Single Leg Romanian Deadlift", "HAMSTRINGS", ["GLUTES"], "DUMBBELL", ["Single Leg RDL", "SL RDL"]),
    ("good_morning", "Good Morning", "HAMSTRINGS", ["GLUTES", "BACK"], "BARBELL", ["Barbell Good Morning"]),
    ("hyperextension", "Hyperextension", "BACK", ["GLUTES", "HAMSTRINGS"], "BODYWEIGHT", ["Back Extension", "45 Degree Hyperextension"]),
    ("reverse_hyperextension", "Reverse Hyperextension", "GLUTES", ["HAMSTRINGS"], "MACHINE", ["Reverse Hyper"]),
    ("superman", "Superman", "BACK", ["GLUTES"], "BODYWEIGHT", []),
    ("resistance_band_row", "Resistance Band Row", "BACK", ["BICEPS"], "RESISTANCE_BAND", ["Band Row"]),
    ("kettlebell_row", "Kettlebell Row", "BACK", ["BICEPS"], "KETTLEBELL", ["KB Row"]),
    ("smith_machine_row", "Smith Machine Row", "BACK", ["BICEPS"], "SMITH_MACHINE", ["Smith Row"]),
    ("wide_grip_cable_row", "Wide Grip Cable Row", "BACK", ["BICEPS"], "CABLE", []),
    ("close_grip_cable_row", "Close Grip Cable Row", "BACK", ["BICEPS"], "CABLE", []),
]:
    add(*e)

# --- SHOULDERS ---
for e in [
    ("overhead_press", "Overhead Press", "SHOULDERS", ["TRICEPS"], "BARBELL", ["OHP", "Barbell Overhead Press", "Military Press", "Shoulder Press"]),
    ("seated_overhead_press", "Seated Overhead Press", "SHOULDERS", ["TRICEPS"], "BARBELL", ["Seated OHP"]),
    ("push_press", "Push Press", "SHOULDERS", ["TRICEPS", "QUADS"], "BARBELL", ["Barbell Push Press"]),
    ("dumbbell_shoulder_press", "Dumbbell Shoulder Press", "SHOULDERS", ["TRICEPS"], "DUMBBELL", ["DB Shoulder Press", "Seated DB Press"]),
    ("arnold_press", "Arnold Press", "SHOULDERS", ["TRICEPS"], "DUMBBELL", ["Arnold DB Press"]),
    ("machine_shoulder_press", "Machine Shoulder Press", "SHOULDERS", ["TRICEPS"], "MACHINE", ["Shoulder Press Machine"]),
    ("smith_machine_shoulder_press", "Smith Machine Shoulder Press", "SHOULDERS", ["TRICEPS"], "SMITH_MACHINE", ["Smith OHP"]),
    ("cable_shoulder_press", "Cable Shoulder Press", "SHOULDERS", ["TRICEPS"], "CABLE", []),
    ("lateral_raise", "Lateral Raise", "SHOULDERS", [], "DUMBBELL", ["Side Raise", "DB Lateral Raise", "Dumbbell Lateral Raise"]),
    ("cable_lateral_raise", "Cable Lateral Raise", "SHOULDERS", [], "CABLE", ["Single Arm Cable Lateral Raise"]),
    ("machine_lateral_raise", "Machine Lateral Raise", "SHOULDERS", [], "MACHINE", ["Lateral Raise Machine"]),
    ("front_raise", "Front Raise", "SHOULDERS", [], "DUMBBELL", ["DB Front Raise", "Dumbbell Front Raise"]),
    ("cable_front_raise", "Cable Front Raise", "SHOULDERS", [], "CABLE", []),
    ("plate_front_raise", "Plate Front Raise", "SHOULDERS", [], "PLATE", []),
    ("rear_delt_fly", "Rear Delt Fly", "SHOULDERS", ["BACK"], "DUMBBELL", ["Bent Over Rear Delt Fly", "Rear Delt Raise"]),
    ("upright_row", "Upright Row", "SHOULDERS", ["TRAPS"], "BARBELL", ["BB Upright Row"]),
    ("dumbbell_upright_row", "Dumbbell Upright Row", "SHOULDERS", ["TRAPS"], "DUMBBELL", ["DB Upright Row"]),
    ("cable_upright_row", "Cable Upright Row", "SHOULDERS", ["TRAPS"], "CABLE", []),
    ("landmine_lateral_raise", "Landmine Lateral Raise", "SHOULDERS", [], "LANDMINE", []),
    ("bus_driver", "Bus Driver", "SHOULDERS", ["CORE"], "OTHER", ["Plate Rotation"]),
    ("cuban_rotation", "Cuban Rotation", "SHOULDERS", [], "DUMBBELL", []),
    ("scarecrow", "Scarecrow", "SHOULDERS", ["BACK"], "DUMBBELL", []),
    ("y_raise", "Y Raise", "SHOULDERS", ["BACK"], "DUMBBELL", ["Prone Y Raise"]),
    ("w_raise", "W Raise", "SHOULDERS", ["BACK"], "DUMBBELL", ["Prone W Raise"]),
    ("resistance_band_lateral_raise", "Resistance Band Lateral Raise", "SHOULDERS", [], "RESISTANCE_BAND", ["Band Lateral Raise"]),
    ("kettlebell_press", "Kettlebell Press", "SHOULDERS", ["TRICEPS"], "KETTLEBELL", ["KB Press"]),
    ("behind_the_neck_press", "Behind The Neck Press", "SHOULDERS", ["TRICEPS"], "BARBELL", ["BTN Press"]),
    ("bradford_press", "Bradford Press", "SHOULDERS", ["TRICEPS"], "BARBELL", []),
    ("lu_raise", "Lu Raise", "SHOULDERS", [], "DUMBBELL", []),
]:
    add(*e)

# --- BICEPS ---
for e in [
    ("barbell_curl", "Barbell Curl", "BICEPS", ["FOREARMS"], "BARBELL", ["BB Curl", "Standing Barbell Curl"]),
    ("ez_bar_curl", "EZ Bar Curl", "BICEPS", ["FOREARMS"], "EZ_BAR", ["EZ Curl", "EZ Bar Bicep Curl"]),
    ("dumbbell_curl", "Dumbbell Curl", "BICEPS", ["FOREARMS"], "DUMBBELL", ["DB Curl", "Alternating Dumbbell Curl"]),
    ("hammer_curl", "Hammer Curl", "BICEPS", ["FOREARMS"], "DUMBBELL", ["DB Hammer Curl", "Neutral Grip Curl"]),
    ("incline_dumbbell_curl", "Incline Dumbbell Curl", "BICEPS", [], "DUMBBELL", ["Incline DB Curl"]),
    ("preacher_curl", "Preacher Curl", "BICEPS", [], "EZ_BAR", ["EZ Preacher Curl"]),
    ("dumbbell_preacher_curl", "Dumbbell Preacher Curl", "BICEPS", [], "DUMBBELL", ["DB Preacher Curl"]),
    ("machine_preacher_curl", "Machine Preacher Curl", "BICEPS", [], "MACHINE", ["Preacher Curl Machine"]),
    ("concentration_curl", "Concentration Curl", "BICEPS", [], "DUMBBELL", ["Seated Concentration Curl"]),
    ("cable_curl", "Cable Curl", "BICEPS", [], "CABLE", ["Standing Cable Curl"]),
    ("cable_hammer_curl", "Cable Hammer Curl", "BICEPS", ["FOREARMS"], "CABLE", ["Rope Hammer Curl"]),
    ("spider_curl", "Spider Curl", "BICEPS", [], "DUMBBELL", ["Incline Spider Curl"]),
    ("drag_curl", "Drag Curl", "BICEPS", [], "BARBELL", ["Barbell Drag Curl"]),
    ("reverse_curl", "Reverse Curl", "FOREARMS", ["BICEPS"], "BARBELL", ["Reverse Barbell Curl"]),
    ("dumbbell_reverse_curl", "Dumbbell Reverse Curl", "FOREARMS", ["BICEPS"], "DUMBBELL", ["Reverse DB Curl"]),
    ("bayesian_curl", "Bayesian Curl", "BICEPS", [], "CABLE", ["Behind Body Cable Curl"]),
    ("cross_body_hammer_curl", "Cross Body Hammer Curl", "BICEPS", ["FOREARMS"], "DUMBBELL", []),
    ("zottman_curl", "Zottman Curl", "BICEPS", ["FOREARMS"], "DUMBBELL", []),
    ("21s_curl", "21s Curl", "BICEPS", [], "BARBELL", ["21 Curl"]),
    ("machine_curl", "Machine Curl", "BICEPS", [], "MACHINE", ["Bicep Curl Machine"]),
    ("resistance_band_curl", "Resistance Band Curl", "BICEPS", [], "RESISTANCE_BAND", ["Band Curl"]),
    ("kettlebell_curl", "Kettlebell Curl", "BICEPS", [], "KETTLEBELL", ["KB Curl"]),
    ("single_arm_cable_curl", "Single Arm Cable Curl", "BICEPS", [], "CABLE", ["One Arm Cable Curl"]),
    ("high_cable_curl", "High Cable Curl", "BICEPS", [], "CABLE", ["Overhead Cable Curl"]),
]:
    add(*e)

# --- TRICEPS ---
for e in [
    ("tricep_pushdown", "Tricep Pushdown", "TRICEPS", [], "CABLE", ["Triceps Pushdown", "Rope Pushdown", "Cable Pushdown"]),
    ("reverse_grip_pushdown", "Reverse Grip Pushdown", "TRICEPS", [], "CABLE", ["Underhand Pushdown"]),
    ("single_arm_pushdown", "Single Arm Pushdown", "TRICEPS", [], "CABLE", ["One Arm Pushdown"]),
    ("overhead_tricep_extension", "Overhead Tricep Extension", "TRICEPS", [], "DUMBBELL", ["DB Overhead Extension", "Seated Overhead Extension"]),
    ("cable_overhead_extension", "Cable Overhead Extension", "TRICEPS", [], "CABLE", ["Rope Overhead Extension"]),
    ("skull_crusher", "Skull Crusher", "TRICEPS", [], "EZ_BAR", ["Lying Tricep Extension", "EZ Bar Skull Crusher"]),
    ("barbell_skull_crusher", "Barbell Skull Crusher", "TRICEPS", [], "BARBELL", ["Lying Barbell Tricep Extension"]),
    ("dumbbell_skull_crusher", "Dumbbell Skull Crusher", "TRICEPS", [], "DUMBBELL", ["DB Skull Crusher"]),
    ("close_grip_bench_press", "Close Grip Bench Press", "TRICEPS", ["CHEST"], "BARBELL", ["CGBP", "Close Grip Bench"]),
    ("dip", "Dip", "TRICEPS", ["CHEST", "SHOULDERS"], "BODYWEIGHT", ["Tricep Dip", "Parallel Bar Dip"]),
    ("bench_dip", "Bench Dip", "TRICEPS", ["CHEST"], "BODYWEIGHT", ["Tricep Bench Dip"]),
    ("machine_dip", "Machine Dip", "TRICEPS", ["CHEST"], "MACHINE", ["Assisted Dip"]),
    ("tricep_kickback", "Tricep Kickback", "TRICEPS", [], "DUMBBELL", ["DB Kickback", "Dumbbell Kickback"]),
    ("cable_kickback", "Cable Kickback", "TRICEPS", [], "CABLE", []),
    ("jm_press", "JM Press", "TRICEPS", ["CHEST"], "BARBELL", []),
    ("tate_press", "Tate Press", "TRICEPS", [], "DUMBBELL", []),
    ("dumbbell_overhead_extension", "Dumbbell Overhead Extension", "TRICEPS", [], "DUMBBELL", ["Standing Overhead Extension"]),
    ("ez_bar_overhead_extension", "EZ Bar Overhead Extension", "TRICEPS", [], "EZ_BAR", []),
    ("machine_tricep_extension", "Machine Tricep Extension", "TRICEPS", [], "MACHINE", ["Tricep Extension Machine"]),
    ("resistance_band_pushdown", "Resistance Band Pushdown", "TRICEPS", [], "RESISTANCE_BAND", ["Band Pushdown"]),
    ("diamond_push_up_tricep", "Diamond Push Up", "TRICEPS", ["CHEST"], "BODYWEIGHT", []),
    ("bodyweight_tricep_extension", "Bodyweight Tricep Extension", "TRICEPS", [], "BODYWEIGHT", ["Bodyweight Skull Crusher"]),
]:
    add(*e)

# --- FOREARMS ---
for e in [
    ("wrist_curl", "Wrist Curl", "FOREARMS", [], "DUMBBELL", ["DB Wrist Curl"]),
    ("reverse_wrist_curl", "Reverse Wrist Curl", "FOREARMS", [], "DUMBBELL", ["Reverse DB Wrist Curl"]),
    ("barbell_wrist_curl", "Barbell Wrist Curl", "FOREARMS", [], "BARBELL", ["BB Wrist Curl"]),
    ("barbell_reverse_wrist_curl", "Barbell Reverse Wrist Curl", "FOREARMS", [], "BARBELL", []),
    ("farmer_walk", "Farmer Walk", "FOREARMS", ["TRAPS", "CORE"], "DUMBBELL", ["Farmers Walk", "Farmer Carry"]),
    ("suitcase_carry", "Suitcase Carry", "FOREARMS", ["CORE"], "DUMBBELL", ["Single Arm Carry"]),
    ("plate_pinch", "Plate Pinch", "FOREARMS", [], "PLATE", ["Pinch Grip Hold"]),
    ("dead_hang", "Dead Hang", "FOREARMS", ["BACK"], "BODYWEIGHT", ["Hang"]),
    ("towel_pull_up", "Towel Pull Up", "FOREARMS", ["BACK", "BICEPS"], "BODYWEIGHT", []),
    ("wrist_roller", "Wrist Roller", "FOREARMS", [], "OTHER", []),
    ("reverse_grip_curl", "Reverse Grip Curl", "FOREARMS", ["BICEPS"], "BARBELL", []),
    ("behind_the_back_wrist_curl", "Behind The Back Wrist Curl", "FOREARMS", [], "BARBELL", []),
]:
    add(*e)

# --- QUADS ---
for e in [
    ("barbell_squat", "Barbell Back Squat", "QUADS", ["GLUTES", "HAMSTRINGS"], "BARBELL", ["Back Squat", "BB Squat", "Barbell Squat", "Squat"]),
    ("front_squat", "Front Squat", "QUADS", ["CORE"], "BARBELL", ["BB Front Squat", "Barbell Front Squat"]),
    ("high_bar_squat", "High Bar Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("low_bar_squat", "Low Bar Squat", "QUADS", ["GLUTES", "HAMSTRINGS"], "BARBELL", []),
    ("box_squat", "Box Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("pause_squat", "Pause Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("goblet_squat", "Goblet Squat", "QUADS", ["GLUTES"], "KETTLEBELL", ["KB Goblet Squat"]),
    ("dumbbell_squat", "Dumbbell Squat", "QUADS", ["GLUTES"], "DUMBBELL", ["DB Squat"]),
    ("hack_squat", "Hack Squat", "QUADS", ["GLUTES"], "MACHINE", ["Machine Hack Squat"]),
    ("leg_press", "Leg Press", "QUADS", ["GLUTES"], "MACHINE", ["Machine Leg Press", "45 Degree Leg Press"]),
    ("single_leg_press", "Single Leg Press", "QUADS", ["GLUTES"], "MACHINE", ["One Leg Press"]),
    ("leg_extension", "Leg Extension", "QUADS", [], "MACHINE", ["Quad Extension"]),
    ("sissy_squat", "Sissy Squat", "QUADS", [], "BODYWEIGHT", []),
    ("split_squat", "Split Squat", "QUADS", ["GLUTES"], "DUMBBELL", ["Static Split Squat"]),
    ("bulgarian_split_squat", "Bulgarian Split Squat", "QUADS", ["GLUTES"], "DUMBBELL", ["BSS", "Rear Foot Elevated Split Squat"]),
    ("walking_lunge", "Walking Lunge", "QUADS", ["GLUTES"], "DUMBBELL", ["Lunge", "Walking Lunges"]),
    ("reverse_lunge", "Reverse Lunge", "QUADS", ["GLUTES"], "DUMBBELL", ["Backward Lunge"]),
    ("forward_lunge", "Forward Lunge", "QUADS", ["GLUTES"], "DUMBBELL", []),
    ("lateral_lunge", "Lateral Lunge", "QUADS", ["GLUTES"], "DUMBBELL", ["Side Lunge"]),
    ("curtsy_lunge", "Curtsy Lunge", "QUADS", ["GLUTES"], "DUMBBELL", []),
    ("step_up", "Step Up", "QUADS", ["GLUTES"], "DUMBBELL", ["Weighted Step Up"]),
    ("smith_machine_squat", "Smith Machine Squat", "QUADS", ["GLUTES"], "SMITH_MACHINE", ["Smith Squat"]),
    ("belt_squat", "Belt Squat", "QUADS", ["GLUTES"], "MACHINE", []),
    ("pendulum_squat", "Pendulum Squat", "QUADS", ["GLUTES"], "MACHINE", []),
    ("v_squat", "V Squat", "QUADS", ["GLUTES"], "MACHINE", []),
    ("wall_sit", "Wall Sit", "QUADS", [], "BODYWEIGHT", []),
    ("pistol_squat", "Pistol Squat", "QUADS", ["GLUTES"], "BODYWEIGHT", ["Single Leg Squat"]),
    ("jump_squat", "Jump Squat", "QUADS", ["GLUTES"], "BODYWEIGHT", []),
    ("resistance_band_squat", "Resistance Band Squat", "QUADS", ["GLUTES"], "RESISTANCE_BAND", ["Band Squat"]),
    ("zercher_squat", "Zercher Squat", "QUADS", ["CORE"], "BARBELL", []),
    ("safety_bar_squat", "Safety Bar Squat", "QUADS", ["GLUTES"], "BARBELL", ["SSB Squat"]),
]:
    add(*e)

# --- HAMSTRINGS ---
for e in [
    ("leg_curl", "Leg Curl", "HAMSTRINGS", [], "MACHINE", ["Hamstring Curl", "Lying Leg Curl"]),
    ("seated_leg_curl", "Seated Leg Curl", "HAMSTRINGS", [], "MACHINE", []),
    ("standing_leg_curl", "Standing Leg Curl", "HAMSTRINGS", [], "MACHINE", ["Single Leg Curl"]),
    ("nordic_curl", "Nordic Curl", "HAMSTRINGS", [], "BODYWEIGHT", ["Nordic Hamstring Curl"]),
    ("glute_ham_raise", "Glute Ham Raise", "HAMSTRINGS", ["GLUTES"], "MACHINE", ["GHR"]),
    ("cable_pull_through", "Cable Pull Through", "HAMSTRINGS", ["GLUTES"], "CABLE", ["Pull Through"]),
    ("kettlebell_swing", "Kettlebell Swing", "HAMSTRINGS", ["GLUTES"], "KETTLEBELL", ["KB Swing", "Russian Swing"]),
    ("single_leg_deadlift", "Single Leg Deadlift", "HAMSTRINGS", ["GLUTES"], "DUMBBELL", ["Single Leg DL"]),
    ("cable_romanian_deadlift", "Cable Romanian Deadlift", "HAMSTRINGS", ["GLUTES"], "CABLE", ["Cable RDL"]),
    ("dumbbell_romanian_deadlift", "Dumbbell Romanian Deadlift", "HAMSTRINGS", ["GLUTES"], "DUMBBELL", ["DB RDL"]),
    ("trap_bar_romanian_deadlift", "Trap Bar Romanian Deadlift", "HAMSTRINGS", ["GLUTES"], "TRAP_BAR", []),
    ("slider_leg_curl", "Slider Leg Curl", "HAMSTRINGS", [], "BODYWEIGHT", []),
    ("resistance_band_leg_curl", "Resistance Band Leg Curl", "HAMSTRINGS", [], "RESISTANCE_BAND", ["Band Leg Curl"]),
    ("reverse_hyper", "Reverse Hyper", "HAMSTRINGS", ["GLUTES"], "MACHINE", ["Reverse Hyperextension"]),
]:
    add(*e)

# --- GLUTES ---
for e in [
    ("hip_thrust", "Hip Thrust", "GLUTES", ["HAMSTRINGS"], "BARBELL", ["Barbell Hip Thrust", "BB Hip Thrust"]),
    ("single_leg_hip_thrust", "Single Leg Hip Thrust", "GLUTES", ["HAMSTRINGS"], "BODYWEIGHT", []),
    ("glute_bridge", "Glute Bridge", "GLUTES", ["HAMSTRINGS"], "BODYWEIGHT", ["Bodyweight Glute Bridge"]),
    ("barbell_glute_bridge", "Barbell Glute Bridge", "GLUTES", ["HAMSTRINGS"], "BARBELL", []),
    ("cable_kickback", "Cable Kickback", "GLUTES", [], "CABLE", ["Glute Kickback"]),
    ("machine_kickback", "Machine Kickback", "GLUTES", [], "MACHINE", ["Glute Kickback Machine"]),
    ("donkey_kick", "Donkey Kick", "GLUTES", [], "BODYWEIGHT", []),
    ("fire_hydrant", "Fire Hydrant", "GLUTES", [], "BODYWEIGHT", []),
    ("clamshell", "Clamshell", "GLUTES", [], "RESISTANCE_BAND", []),
    ("frog_pump", "Frog Pump", "GLUTES", [], "BODYWEIGHT", []),
    ("cable_hip_abduction", "Cable Hip Abduction", "GLUTES", [], "CABLE", []),
    ("machine_hip_abduction", "Machine Hip Abduction", "GLUTES", [], "MACHINE", ["Hip Abductor Machine"]),
    ("machine_hip_adduction", "Machine Hip Adduction", "GLUTES", [], "MACHINE", ["Hip Adductor Machine"]),
    ("sumo_deadlift_glutes", "Sumo Deadlift", "GLUTES", ["QUADS", "BACK"], "BARBELL", []),
    ("step_up_glutes", "Step Up", "GLUTES", ["QUADS"], "DUMBBELL", []),
    ("smith_machine_hip_thrust", "Smith Machine Hip Thrust", "GLUTES", ["HAMSTRINGS"], "SMITH_MACHINE", []),
    ("kettlebell_hip_thrust", "Kettlebell Hip Thrust", "GLUTES", ["HAMSTRINGS"], "KETTLEBELL", []),
    ("banded_hip_thrust", "Banded Hip Thrust", "GLUTES", ["HAMSTRINGS"], "RESISTANCE_BAND", []),
]:
    add(*e)

# --- CALVES ---
for e in [
    ("standing_calf_raise", "Standing Calf Raise", "CALVES", [], "MACHINE", ["Calf Raise", "Machine Calf Raise"]),
    ("seated_calf_raise", "Seated Calf Raise", "CALVES", [], "MACHINE", []),
    ("donkey_calf_raise", "Donkey Calf Raise", "CALVES", [], "MACHINE", []),
    ("leg_press_calf_raise", "Leg Press Calf Raise", "CALVES", [], "MACHINE", ["Calf Press"]),
    ("smith_machine_calf_raise", "Smith Machine Calf Raise", "CALVES", [], "SMITH_MACHINE", []),
    ("dumbbell_calf_raise", "Dumbbell Calf Raise", "CALVES", [], "DUMBBELL", ["DB Calf Raise"]),
    ("barbell_calf_raise", "Barbell Calf Raise", "CALVES", [], "BARBELL", []),
    ("single_leg_calf_raise", "Single Leg Calf Raise", "CALVES", [], "DUMBBELL", ["One Leg Calf Raise"]),
    ("calf_raise", "Calf Raise", "CALVES", [], "BODYWEIGHT", ["Bodyweight Calf Raise"]),
    ("tibialis_raise", "Tibialis Raise", "CALVES", [], "BODYWEIGHT", ["Tib Raise"]),
    ("seated_calf_press", "Seated Calf Press", "CALVES", [], "MACHINE", []),
]:
    add(*e)

# --- CORE ---
for e in [
    ("plank", "Plank", "CORE", ["SHOULDERS"], "BODYWEIGHT", ["Front Plank"]),
    ("side_plank", "Side Plank", "CORE", [], "BODYWEIGHT", []),
    ("rkc_plank", "RKC Plank", "CORE", [], "BODYWEIGHT", []),
    ("cable_crunch", "Cable Crunch", "CORE", [], "CABLE", ["Kneeling Cable Crunch"]),
    ("crunch", "Crunch", "CORE", [], "BODYWEIGHT", ["Ab Crunch"]),
    ("bicycle_crunch", "Bicycle Crunch", "CORE", [], "BODYWEIGHT", []),
    ("reverse_crunch", "Reverse Crunch", "CORE", [], "BODYWEIGHT", []),
    ("sit_up", "Sit Up", "CORE", [], "BODYWEIGHT", ["Situp"]),
    ("decline_sit_up", "Decline Sit Up", "CORE", [], "BODYWEIGHT", []),
    ("hanging_leg_raise", "Hanging Leg Raise", "CORE", ["FOREARMS"], "BODYWEIGHT", ["Leg Raise", "Hanging Knee Raise"]),
    ("hanging_knee_raise", "Hanging Knee Raise", "CORE", [], "BODYWEIGHT", []),
    ("captains_chair_leg_raise", "Captains Chair Leg Raise", "CORE", [], "MACHINE", ["Captain Chair Raise"]),
    ("lying_leg_raise", "Lying Leg Raise", "CORE", [], "BODYWEIGHT", []),
    ("v_up", "V Up", "CORE", [], "BODYWEIGHT", ["V-Up"]),
    ("toe_touch", "Toe Touch", "CORE", [], "BODYWEIGHT", []),
    ("russian_twist", "Russian Twist", "CORE", [], "BODYWEIGHT", ["Weighted Russian Twist"]),
    ("woodchopper", "Woodchopper", "CORE", [], "CABLE", ["Cable Woodchopper"]),
    ("pallof_press", "Pallof Press", "CORE", [], "CABLE", ["Anti Rotation Press"]),
    ("ab_wheel_rollout", "Ab Wheel Rollout", "CORE", ["SHOULDERS"], "OTHER", ["Ab Rollout"]),
    ("dead_bug", "Dead Bug", "CORE", [], "BODYWEIGHT", []),
    ("bird_dog", "Bird Dog", "CORE", ["BACK"], "BODYWEIGHT", []),
    ("mountain_climber", "Mountain Climber", "CORE", ["QUADS"], "BODYWEIGHT", []),
    ("flutter_kick", "Flutter Kick", "CORE", [], "BODYWEIGHT", []),
    ("hollow_hold", "Hollow Hold", "CORE", [], "BODYWEIGHT", []),
    ("dragon_flag", "Dragon Flag", "CORE", [], "BODYWEIGHT", []),
    ("copenhagen_plank", "Copenhagen Plank", "CORE", ["GLUTES"], "BODYWEIGHT", []),
    ("suitcase_crunch", "Suitcase Crunch", "CORE", [], "DUMBBELL", []),
    ("machine_crunch", "Machine Crunch", "CORE", [], "MACHINE", ["Ab Crunch Machine"]),
    ("decline_crunch", "Decline Crunch", "CORE", [], "BODYWEIGHT", []),
    ("landmine_rotation", "Landmine Rotation", "CORE", [], "LANDMINE", []),
    ("resistance_band_crunch", "Resistance Band Crunch", "CORE", [], "RESISTANCE_BAND", []),
    ("farmers_walk_core", "Farmer Walk", "CORE", ["FOREARMS"], "DUMBBELL", []),
    ("windshield_wiper", "Windshield Wiper", "CORE", [], "BODYWEIGHT", []),
    ("cable_side_bend", "Cable Side Bend", "CORE", [], "CABLE", []),
    ("dumbbell_side_bend", "Dumbbell Side Bend", "CORE", [], "DUMBBELL", []),
    ("turkish_get_up", "Turkish Get Up", "CORE", ["SHOULDERS"], "KETTLEBELL", ["TGU"]),
]:
    add(*e)

# --- TRAPS ---
for e in [
    ("barbell_shrug", "Barbell Shrug", "TRAPS", [], "BARBELL", ["BB Shrug"]),
    ("dumbbell_shrug", "Dumbbell Shrug", "TRAPS", [], "DUMBBELL", ["DB Shrug"]),
    ("trap_bar_shrug", "Trap Bar Shrug", "TRAPS", [], "TRAP_BAR", []),
    ("smith_machine_shrug", "Smith Machine Shrug", "TRAPS", [], "SMITH_MACHINE", []),
    ("cable_shrug", "Cable Shrug", "TRAPS", [], "CABLE", []),
    ("machine_shrug", "Machine Shrug", "TRAPS", [], "MACHINE", []),
    ("power_shrug", "Power Shrug", "TRAPS", ["GLUTES"], "BARBELL", []),
    ("behind_the_back_shrug", "Behind The Back Shrug", "TRAPS", [], "BARBELL", []),
    ("overhead_shrug", "Overhead Shrug", "TRAPS", ["SHOULDERS"], "BARBELL", []),
    ("farmer_walk_traps", "Farmer Walk", "TRAPS", ["FOREARMS"], "DUMBBELL", []),
]:
    add(*e)

# --- FULL BODY ---
for e in [
    ("clean", "Clean", "FULL_BODY", ["QUADS", "BACK"], "BARBELL", ["Power Clean"]),
    ("hang_clean", "Hang Clean", "FULL_BODY", ["QUADS", "BACK"], "BARBELL", []),
    ("snatch", "Snatch", "FULL_BODY", ["QUADS", "SHOULDERS"], "BARBELL", ["Power Snatch"]),
    ("hang_snatch", "Hang Snatch", "FULL_BODY", ["QUADS", "SHOULDERS"], "BARBELL", []),
    ("clean_and_jerk", "Clean And Jerk", "FULL_BODY", ["QUADS", "SHOULDERS"], "BARBELL", []),
    ("thruster", "Thruster", "FULL_BODY", ["QUADS", "SHOULDERS"], "BARBELL", ["Barbell Thruster"]),
    ("dumbbell_thruster", "Dumbbell Thruster", "FULL_BODY", ["QUADS", "SHOULDERS"], "DUMBBELL", ["DB Thruster"]),
    ("kettlebell_clean", "Kettlebell Clean", "FULL_BODY", ["BACK"], "KETTLEBELL", ["KB Clean"]),
    ("kettlebell_snatch", "Kettlebell Snatch", "FULL_BODY", ["SHOULDERS"], "KETTLEBELL", ["KB Snatch"]),
    ("burpee", "Burpee", "FULL_BODY", ["CHEST", "QUADS"], "BODYWEIGHT", []),
    ("man_maker", "Man Maker", "FULL_BODY", ["CHEST", "SHOULDERS"], "DUMBBELL", []),
    ("devil_press", "Devil Press", "FULL_BODY", ["CHEST", "SHOULDERS"], "DUMBBELL", []),
    ("wall_ball", "Wall Ball", "FULL_BODY", ["QUADS", "SHOULDERS"], "OTHER", ["Wall Ball Shot"]),
    ("battle_rope", "Battle Rope", "FULL_BODY", ["SHOULDERS", "CORE"], "OTHER", ["Rope Slam"]),
    ("sled_push", "Sled Push", "FULL_BODY", ["QUADS", "GLUTES"], "OTHER", ["Prowler Push"]),
    ("sled_pull", "Sled Pull", "FULL_BODY", ["BACK", "HAMSTRINGS"], "OTHER", ["Prowler Pull"]),
    ("tire_flip", "Tire Flip", "FULL_BODY", ["BACK", "QUADS"], "OTHER", []),
    ("bear_crawl", "Bear Crawl", "FULL_BODY", ["CORE", "SHOULDERS"], "BODYWEIGHT", []),
    ("box_jump", "Box Jump", "FULL_BODY", ["QUADS", "GLUTES"], "BODYWEIGHT", []),
    ("broad_jump", "Broad Jump", "FULL_BODY", ["QUADS", "GLUTES"], "BODYWEIGHT", []),
    ("medicine_ball_slam", "Medicine Ball Slam", "FULL_BODY", ["CORE", "SHOULDERS"], "OTHER", ["Ball Slam"]),
    ("medicine_ball_throw", "Medicine Ball Throw", "FULL_BODY", ["CORE"], "OTHER", []),
    ("kettlebell_clean_and_press", "Kettlebell Clean And Press", "FULL_BODY", ["SHOULDERS"], "KETTLEBELL", []),
    ("sandbag_carry", "Sandbag Carry", "FULL_BODY", ["CORE", "TRAPS"], "OTHER", []),
    ("rower", "Rower", "FULL_BODY", ["BACK", "QUADS"], "MACHINE", ["Rowing Machine"]),
    ("ski_erg", "Ski Erg", "FULL_BODY", ["BACK", "TRICEPS"], "MACHINE", []),
    ("assault_bike", "Assault Bike", "FULL_BODY", ["QUADS"], "MACHINE", ["Air Bike"]),
    ("jump_rope", "Jump Rope", "FULL_BODY", ["CALVES"], "OTHER", ["Skipping Rope"]),
]:
    add(*e)

# --- Additional exercises to reach comprehensive coverage ---
for e in [
    # More chest
    ("machine_fly", "Machine Fly", "CHEST", [], "MACHINE", ["Pec Fly Machine"]),
    ("hammer_strength_chest_press", "Hammer Strength Chest Press", "CHEST", ["TRICEPS"], "MACHINE", []),
    ("isometric_chest_squeeze", "Isometric Chest Squeeze", "CHEST", [], "OTHER", ["Plate Squeeze"]),
    ("weighted_push_up", "Weighted Push Up", "CHEST", ["TRICEPS"], "BODYWEIGHT", []),
    ("archer_push_up", "Archer Push Up", "CHEST", ["TRICEPS"], "BODYWEIGHT", []),
    ("ring_push_up", "Ring Push Up", "CHEST", ["TRICEPS", "CORE"], "BODYWEIGHT", []),
    ("deficit_push_up", "Deficit Push Up", "CHEST", ["TRICEPS"], "BODYWEIGHT", []),
    ("clap_push_up", "Clap Push Up", "CHEST", ["TRICEPS"], "BODYWEIGHT", ["Plyometric Push Up"]),
    # More back
    ("kroc_row", "Kroc Row", "BACK", ["BICEPS"], "DUMBBELL", ["Heavy DB Row"]),
    ("seal_row", "Seal Row", "BACK", ["BICEPS"], "BARBELL", ["Barbell Seal Row"]),
    ("helms_row", "Helms Row", "BACK", ["BICEPS"], "DUMBBELL", ["Chest Supported Helms Row"]),
    ("chest_supported_t_bar_row", "Chest Supported T Bar Row", "BACK", ["BICEPS"], "MACHINE", []),
    ("lat_pullover_machine", "Lat Pullover Machine", "BACK", ["CHEST"], "MACHINE", []),
    ("assisted_pull_up", "Assisted Pull Up", "BACK", ["BICEPS"], "MACHINE", ["Assisted Chin Up"]),
    ("muscle_up", "Muscle Up", "BACK", ["CHEST", "TRICEPS"], "BODYWEIGHT", []),
    ("renegade_row", "Renegade Row", "BACK", ["CORE"], "DUMBBELL", ["Plank Row"]),
    ("bent_over_row", "Bent Over Row", "BACK", ["BICEPS"], "DUMBBELL", ["Two Arm DB Row"]),
    ("single_arm_cable_row", "Single Arm Cable Row", "BACK", ["BICEPS"], "CABLE", ["One Arm Cable Row"]),
    ("kayak_row", "Kayak Row", "BACK", ["CORE"], "CABLE", []),
    ("jefferson_deadlift", "Jefferson Deadlift", "BACK", ["GLUTES", "QUADS"], "BARBELL", []),
    ("deficit_deadlift", "Deficit Deadlift", "BACK", ["HAMSTRINGS", "GLUTES"], "BARBELL", []),
    ("block_pull", "Block Pull", "BACK", ["GLUTES", "HAMSTRINGS"], "BARBELL", []),
    ("snatch_grip_deadlift", "Snatch Grip Deadlift", "BACK", ["HAMSTRINGS", "GLUTES"], "BARBELL", []),
    # More shoulders
    ("seated_dumbbell_lateral_raise", "Seated Dumbbell Lateral Raise", "SHOULDERS", [], "DUMBBELL", []),
    ("leaning_lateral_raise", "Leaning Lateral Raise", "SHOULDERS", [], "CABLE", []),
    ("incline_lateral_raise", "Incline Lateral Raise", "SHOULDERS", [], "DUMBBELL", []),
    ("reverse_pec_deck", "Reverse Pec Deck", "SHOULDERS", ["BACK"], "MACHINE", []),
    ("cable_y_raise", "Cable Y Raise", "SHOULDERS", ["BACK"], "CABLE", []),
    ("plate_raise", "Plate Raise", "SHOULDERS", [], "PLATE", ["Front Plate Raise"]),
    ("kettlebell_halos", "Kettlebell Halos", "SHOULDERS", ["CORE"], "KETTLEBELL", ["KB Halos"]),
    ("bottoms_up_press", "Bottoms Up Press", "SHOULDERS", ["CORE"], "KETTLEBELL", []),
    ("z_press", "Z Press", "SHOULDERS", ["CORE"], "BARBELL", ["Seated Floor Press"]),
    ("handstand_push_up", "Handstand Push Up", "SHOULDERS", ["TRICEPS"], "BODYWEIGHT", ["HSPU"]),
    ("pike_push_up", "Pike Push Up", "SHOULDERS", ["TRICEPS"], "BODYWEIGHT", []),
    ("landmine_press_shoulder", "Landmine Shoulder Press", "SHOULDERS", ["CHEST"], "LANDMINE", []),
    # More biceps
    ("incline_hammer_curl", "Incline Hammer Curl", "BICEPS", ["FOREARMS"], "DUMBBELL", []),
    ("machine_hammer_curl", "Machine Hammer Curl", "BICEPS", ["FOREARMS"], "MACHINE", []),
    ("cable_preacher_curl", "Cable Preacher Curl", "BICEPS", [], "CABLE", []),
    ("reverse_ez_bar_curl", "Reverse EZ Bar Curl", "FOREARMS", ["BICEPS"], "EZ_BAR", []),
    ("waiter_curl", "Waiter Curl", "BICEPS", [], "DUMBBELL", []),
    ("cheat_curl", "Cheat Curl", "BICEPS", [], "BARBELL", []),
    ("larsen_press_curl", "Larsen Press Curl", "BICEPS", [], "BARBELL", []),
    # More triceps
    ("board_press", "Board Press", "TRICEPS", ["CHEST"], "BARBELL", []),
    ("floor_skull_crusher", "Floor Skull Crusher", "TRICEPS", [], "EZ_BAR", []),
    ("rolling_tricep_extension", "Rolling Tricep Extension", "TRICEPS", [], "DUMBBELL", []),
    ("cross_body_tricep_extension", "Cross Body Tricep Extension", "TRICEPS", [], "DUMBBELL", []),
    ("band_tricep_extension", "Band Tricep Extension", "TRICEPS", [], "RESISTANCE_BAND", []),
    ("ring_dip", "Ring Dip", "TRICEPS", ["CHEST"], "BODYWEIGHT", []),
    ("weighted_dip", "Weighted Dip", "TRICEPS", ["CHEST"], "BODYWEIGHT", []),
    # More quads
    ("anderson_squat", "Anderson Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("overhead_squat", "Overhead Squat", "QUADS", ["SHOULDERS", "CORE"], "BARBELL", ["OHS"]),
    ("cyclist_squat", "Cyclist Squat", "QUADS", [], "BARBELL", []),
    ("heels_elevated_squat", "Heels Elevated Squat", "QUADS", ["GLUTES"], "BARBELL", ["Heel Raised Squat"]),
    ("spanish_squat", "Spanish Squat", "QUADS", [], "RESISTANCE_BAND", []),
    ("terminal_knee_extension", "Terminal Knee Extension", "QUADS", [], "RESISTANCE_BAND", ["TKE"]),
    ("peterson_step_up", "Peterson Step Up", "QUADS", [], "DUMBBELL", []),
    ("atg_split_squat", "ATG Split Squat", "QUADS", ["GLUTES"], "DUMBBELL", ["Ass To Grass Split Squat"]),
    ("jefferson_squat", "Jefferson Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("cossack_squat", "Cossack Squat", "QUADS", ["GLUTES"], "BODYWEIGHT", []),
    ("shrimp_squat", "Shrimp Squat", "QUADS", ["GLUTES"], "BODYWEIGHT", []),
    ("tempo_squat", "Tempo Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("pin_squat", "Pin Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("hatfield_squat", "Hatfield Squat", "QUADS", ["GLUTES"], "BARBELL", []),
    ("prowler_sprint", "Prowler Sprint", "QUADS", ["GLUTES"], "OTHER", []),
    # More hamstrings / glutes
    ("single_leg_glute_bridge", "Single Leg Glute Bridge", "GLUTES", ["HAMSTRINGS"], "BODYWEIGHT", []),
    ("copenhagen_adduction", "Copenhagen Adduction", "GLUTES", ["CORE"], "BODYWEIGHT", []),
    ("cable_hip_hinge", "Cable Hip Hinge", "HAMSTRINGS", ["GLUTES"], "CABLE", []),
    ("back_extension_45", "45 Degree Back Extension", "HAMSTRINGS", ["GLUTES", "BACK"], "MACHINE", []),
    ("seated_good_morning", "Seated Good Morning", "HAMSTRINGS", ["BACK"], "BARBELL", []),
    ("banded_good_morning", "Banded Good Morning", "HAMSTRINGS", ["GLUTES"], "RESISTANCE_BAND", []),
    ("kettlebell_deadlift", "Kettlebell Deadlift", "HAMSTRINGS", ["GLUTES"], "KETTLEBELL", ["KB Deadlift"]),
    ("trap_bar_shrug_deadlift", "Trap Bar Shrug", "TRAPS", [], "TRAP_BAR", []),
    # More calves
    ("tib_bar_raise", "Tib Bar Raise", "CALVES", [], "OTHER", ["Tibialis Bar"]),
    ("toe_raise", "Toe Raise", "CALVES", [], "BODYWEIGHT", []),
    ("jump_calf_raise", "Jump Calf Raise", "CALVES", [], "BODYWEIGHT", []),
    # More core
    ("stability_ball_crunch", "Stability Ball Crunch", "CORE", [], "OTHER", ["Swiss Ball Crunch"]),
    ("stability_ball_rollout", "Stability Ball Rollout", "CORE", [], "OTHER", []),
    ("suitcase_deadlift", "Suitcase Deadlift", "CORE", ["BACK"], "DUMBBELL", []),
    ("cable_anti_rotation", "Cable Anti Rotation", "CORE", [], "CABLE", []),
    ("stir_the_pot", "Stir The Pot", "CORE", ["SHOULDERS"], "OTHER", ["Stability Ball Stir"]),
    ("hanging_windshield_wiper", "Hanging Windshield Wiper", "CORE", [], "BODYWEIGHT", []),
    ("l_sit", "L Sit", "CORE", ["TRICEPS"], "BODYWEIGHT", []),
    ("dragon_walk", "Dragon Walk", "CORE", ["SHOULDERS"], "BODYWEIGHT", []),
    ("ab_coaster", "Ab Coaster", "CORE", [], "MACHINE", []),
    ("decline_leg_raise", "Decline Leg Raise", "CORE", [], "BODYWEIGHT", []),
    ("jackknife", "Jackknife", "CORE", [], "BODYWEIGHT", []),
    ("heel_touch", "Heel Touch", "CORE", [], "BODYWEIGHT", []),
    ("cable_crunch_kneeling", "Kneeling Cable Crunch", "CORE", [], "CABLE", []),
    ("weighted_plank", "Weighted Plank", "CORE", [], "OTHER", []),
    ("copenhagen_raise", "Copenhagen Raise", "CORE", ["GLUTES"], "BODYWEIGHT", []),
    # More full body / conditioning
    ("clean_pull", "Clean Pull", "FULL_BODY", ["BACK", "QUADS"], "BARBELL", []),
    ("snatch_pull", "Snatch Pull", "FULL_BODY", ["BACK", "QUADS"], "BARBELL", []),
    ("push_jerk", "Push Jerk", "FULL_BODY", ["SHOULDERS", "QUADS"], "BARBELL", []),
    ("split_jerk", "Split Jerk", "FULL_BODY", ["SHOULDERS", "QUADS"], "BARBELL", []),
    ("kettlebell_swing_american", "American Kettlebell Swing", "FULL_BODY", ["SHOULDERS"], "KETTLEBELL", []),
    ("kettlebell_goblet_carry", "Kettlebell Goblet Carry", "FULL_BODY", ["CORE"], "KETTLEBELL", []),
    ("farmers_carry", "Farmers Carry", "FULL_BODY", ["FOREARMS", "TRAPS"], "DUMBBELL", []),
    ("overhead_carry", "Overhead Carry", "FULL_BODY", ["SHOULDERS", "CORE"], "DUMBBELL", []),
    ("yoke_walk", "Yoke Walk", "FULL_BODY", ["QUADS", "TRAPS"], "OTHER", []),
    ("atlas_stone", "Atlas Stone", "FULL_BODY", ["BACK", "QUADS"], "OTHER", ["Stone Lift"]),
    ("log_press", "Log Press", "FULL_BODY", ["SHOULDERS"], "OTHER", []),
    ("dumbbell_snatch", "Dumbbell Snatch", "FULL_BODY", ["SHOULDERS"], "DUMBBELL", ["DB Snatch"]),
    ("dumbbell_clean", "Dumbbell Clean", "FULL_BODY", ["BACK"], "DUMBBELL", ["DB Clean"]),
    ("shadow_boxing", "Shadow Boxing", "FULL_BODY", ["SHOULDERS"], "BODYWEIGHT", []),
    ("stair_climber", "Stair Climber", "FULL_BODY", ["QUADS", "GLUTES"], "MACHINE", []),
    ("treadmill_run", "Treadmill Run", "FULL_BODY", ["QUADS", "CALVES"], "MACHINE", []),
    ("elliptical", "Elliptical", "FULL_BODY", ["QUADS"], "MACHINE", []),
    ("spin_bike", "Spin Bike", "FULL_BODY", ["QUADS"], "MACHINE", ["Stationary Bike"]),
    ("sprint", "Sprint", "FULL_BODY", ["QUADS", "CALVES"], "BODYWEIGHT", []),
    ("shuttle_run", "Shuttle Run", "FULL_BODY", ["QUADS"], "BODYWEIGHT", []),
    ("high_knees", "High Knees", "FULL_BODY", ["QUADS", "CALVES"], "BODYWEIGHT", []),
    ("butt_kicks", "Butt Kicks", "FULL_BODY", ["HAMSTRINGS", "CALVES"], "BODYWEIGHT", []),
    ("lateral_shuffle", "Lateral Shuffle", "FULL_BODY", ["QUADS", "GLUTES"], "BODYWEIGHT", []),
    ("inchworm", "Inchworm", "FULL_BODY", ["CORE", "HAMSTRINGS"], "BODYWEIGHT", []),
    ("duck_walk", "Duck Walk", "FULL_BODY", ["QUADS", "GLUTES"], "BODYWEIGHT", []),
    ("crab_walk", "Crab Walk", "FULL_BODY", ["TRICEPS", "GLUTES"], "BODYWEIGHT", []),
    ("turkish_get_up_kettlebell", "Kettlebell Turkish Get Up", "FULL_BODY", ["SHOULDERS", "CORE"], "KETTLEBELL", []),
    ("sandbag_clean", "Sandbag Clean", "FULL_BODY", ["BACK", "QUADS"], "OTHER", []),
    ("sandbag_squat", "Sandbag Squat", "FULL_BODY", ["QUADS", "GLUTES"], "OTHER", []),
    ("landmine_squat", "Landmine Squat", "FULL_BODY", ["QUADS", "GLUTES"], "LANDMINE", []),
    ("landmine_deadlift", "Landmine Deadlift", "FULL_BODY", ["BACK", "HAMSTRINGS"], "LANDMINE", []),
    ("cable_squat", "Cable Squat", "FULL_BODY", ["QUADS", "GLUTES"], "CABLE", []),
    ("smith_machine_lunge", "Smith Machine Lunge", "QUADS", ["GLUTES"], "SMITH_MACHINE", []),
    ("smith_machine_split_squat", "Smith Machine Split Squat", "QUADS", ["GLUTES"], "SMITH_MACHINE", []),
    ("smith_machine_calf_raise_standing", "Smith Machine Standing Calf Raise", "CALVES", [], "SMITH_MACHINE", []),
    ("cable_glute_kickback", "Cable Glute Kickback", "GLUTES", [], "CABLE", []),
    ("reverse_lunge_barbell", "Barbell Reverse Lunge", "QUADS", ["GLUTES"], "BARBELL", []),
    ("walking_lunge_barbell", "Barbell Walking Lunge", "QUADS", ["GLUTES"], "BARBELL", []),
    ("overhead_lunge", "Overhead Lunge", "QUADS", ["SHOULDERS", "CORE"], "DUMBBELL", []),
    ("deficit_lunge", "Deficit Lunge", "QUADS", ["GLUTES"], "DUMBBELL", []),
    ("elevated_split_squat", "Elevated Split Squat", "QUADS", ["GLUTES"], "DUMBBELL", []),
    ("front_foot_elevated_split_squat", "Front Foot Elevated Split Squat", "QUADS", ["GLUTES"], "DUMBBELL", ["FFESS"]),
    ("crossover_lunge", "Crossover Lunge", "QUADS", ["GLUTES"], "DUMBBELL", []),
    ("lateral_step_up", "Lateral Step Up", "QUADS", ["GLUTES"], "DUMBBELL", []),
    ("box_step_down", "Box Step Down", "QUADS", ["GLUTES"], "BODYWEIGHT", []),
    ("single_leg_box_squat", "Single Leg Box Squat", "QUADS", ["GLUTES"], "BODYWEIGHT", []),
    ("trap_bar_shrug_standing", "Standing Trap Bar Shrug", "TRAPS", [], "TRAP_BAR", []),
    ("cable_external_rotation", "Cable External Rotation", "SHOULDERS", [], "CABLE", ["Rotator Cuff External Rotation"]),
    ("cable_internal_rotation", "Cable Internal Rotation", "SHOULDERS", [], "CABLE", ["Rotator Cuff Internal Rotation"]),
    ("band_pull_apart", "Band Pull Apart", "BACK", ["SHOULDERS"], "RESISTANCE_BAND", []),
    ("prone_y_raise", "Prone Y Raise", "SHOULDERS", ["BACK"], "DUMBBELL", []),
    ("prone_t_raise", "Prone T Raise", "SHOULDERS", ["BACK"], "DUMBBELL", []),
    ("prone_i_raise", "Prone I Raise", "SHOULDERS", ["BACK"], "DUMBBELL", []),
    ("wall_slide", "Wall Slide", "SHOULDERS", [], "BODYWEIGHT", []),
    ("scaption", "Scaption", "SHOULDERS", [], "DUMBBELL", ["Scapular Plane Raise"]),
    ("cable_scaption", "Cable Scaption", "SHOULDERS", [], "CABLE", []),
    ("inverted_row_feet_elevated", "Feet Elevated Inverted Row", "BACK", ["BICEPS"], "BODYWEIGHT", []),
    ("trx_row", "Suspension Row", "BACK", ["BICEPS"], "SUSPENSION", ["TRX Row"]),
    ("trx_push_up", "Suspension Push Up", "CHEST", ["TRICEPS", "CORE"], "SUSPENSION", ["TRX Push Up"]),
    ("ring_row", "Ring Row", "BACK", ["BICEPS"], "OTHER", []),
    ("cable_high_row", "Cable High Row", "BACK", ["BICEPS"], "CABLE", []),
    ("cable_low_row", "Cable Low Row", "BACK", ["BICEPS"], "CABLE", []),
    ("hammer_strength_row", "Hammer Strength Row", "BACK", ["BICEPS"], "MACHINE", []),
    ("hammer_strength_high_row", "Hammer Strength High Row", "BACK", ["BICEPS"], "MACHINE", []),
    ("hammer_strength_low_row", "Hammer Strength Low Row", "BACK", ["BICEPS"], "MACHINE", []),
    ("iso_lateral_row", "Iso Lateral Row", "BACK", ["BICEPS"], "MACHINE", []),
    ("chest_supported_barbell_row", "Chest Supported Barbell Row", "BACK", ["BICEPS"], "BARBELL", []),
    ("underhand_barbell_row", "Underhand Barbell Row", "BACK", ["BICEPS"], "BARBELL", []),
    ("overhand_dumbbell_row", "Overhand Dumbbell Row", "BACK", ["BICEPS"], "DUMBBELL", []),
    ("kettlebell_gorilla_row", "Kettlebell Gorilla Row", "BACK", ["BICEPS"], "KETTLEBELL", []),
    ("meadows_landmine_row", "Meadows Landmine Row", "BACK", ["BICEPS"], "LANDMINE", []),
    ("cable_single_arm_pulldown", "Single Arm Cable Pulldown", "BACK", ["BICEPS"], "CABLE", []),
    ("machine_assisted_chin_up", "Machine Assisted Chin Up", "BACK", ["BICEPS"], "MACHINE", []),
    ("lat_pulldown_neutral", "Neutral Grip Lat Pulldown", "BACK", ["BICEPS"], "CABLE", []),
    ("lat_pulldown_v_bar", "V Bar Lat Pulldown", "BACK", ["BICEPS"], "CABLE", []),
    ("lat_pulldown_rope", "Rope Lat Pulldown", "BACK", ["BICEPS"], "CABLE", []),
    ("decline_barbell_bench", "Decline Barbell Bench Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    ("decline_dumbbell_fly", "Decline Dumbbell Fly", "CHEST", [], "DUMBBELL", []),
    ("incline_cable_fly", "Incline Cable Fly", "CHEST", [], "CABLE", []),
    ("decline_cable_fly", "Decline Cable Fly", "CHEST", [], "CABLE", []),
    ("machine_incline_press", "Machine Incline Press", "CHEST", ["SHOULDERS"], "MACHINE", []),
    ("machine_decline_press", "Machine Decline Press", "CHEST", ["TRICEPS"], "MACHINE", []),
    ("smith_machine_decline_press", "Smith Machine Decline Press", "CHEST", ["TRICEPS"], "SMITH_MACHINE", []),
    ("cable_press_incline", "Incline Cable Press", "CHEST", ["SHOULDERS"], "CABLE", []),
    ("squeeze_press", "Squeeze Press", "CHEST", ["TRICEPS"], "DUMBBELL", ["Crush Press"]),
    ("hex_press", "Hex Press", "CHEST", ["TRICEPS"], "DUMBBELL", []),
    ("floor_fly", "Floor Fly", "CHEST", [], "DUMBBELL", ["DB Floor Fly"]),
    ("banded_push_up", "Banded Push Up", "CHEST", ["TRICEPS"], "RESISTANCE_BAND", []),
    ("tempo_bench_press", "Tempo Bench Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    ("spoto_press", "Spoto Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    ("pin_press", "Pin Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    ("larsen_press", "Larsen Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    # Final batch toward 500+
    ("single_arm_cable_crossover", "Single Arm Cable Crossover", "CHEST", [], "CABLE", []),
    ("machine_decline_fly", "Machine Decline Fly", "CHEST", [], "MACHINE", []),
    ("reverse_grip_bench_press", "Reverse Grip Bench Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    ("wide_grip_bench_press", "Wide Grip Bench Press", "CHEST", [], "BARBELL", []),
    ("narrow_grip_bench_press", "Narrow Grip Bench Press", "CHEST", ["TRICEPS"], "BARBELL", []),
    ("cable_pullover_back", "Cable Pullover", "BACK", ["CHEST"], "CABLE", []),
    ("wide_grip_pull_up", "Wide Grip Pull Up", "BACK", ["BICEPS"], "BODYWEIGHT", []),
    ("close_grip_pull_up", "Close Grip Pull Up", "BACK", ["BICEPS"], "BODYWEIGHT", []),
    ("cable_shrug", "Cable Shrug", "TRAPS", [], "CABLE", []),
    ("dumbbell_pullover_back", "Dumbbell Pullover", "BACK", ["CHEST"], "DUMBBELL", []),
    ("chest_supported_machine_row", "Chest Supported Machine Row", "BACK", ["BICEPS"], "MACHINE", []),
    ("single_arm_dumbbell_pullover", "Single Arm Dumbbell Pullover", "BACK", ["CHEST"], "DUMBBELL", []),
    ("cable_single_arm_lateral_raise", "Single Arm Cable Lateral Raise", "SHOULDERS", [], "CABLE", []),
    ("seated_arnold_press", "Seated Arnold Press", "SHOULDERS", ["TRICEPS"], "DUMBBELL", []),
    ("cable_reverse_fly_shoulder", "Cable Reverse Fly", "SHOULDERS", ["BACK"], "CABLE", []),
    ("incline_hammer_curl_seated", "Seated Incline Hammer Curl", "BICEPS", ["FOREARMS"], "DUMBBELL", []),
    ("overhead_cable_curl", "Overhead Cable Curl", "BICEPS", [], "CABLE", []),
    ("single_arm_overhead_extension", "Single Arm Overhead Extension", "TRICEPS", [], "DUMBBELL", []),
    ("cable_rope_overhead_extension", "Cable Rope Overhead Extension", "TRICEPS", [], "CABLE", []),
    ("safety_bar_walking_lunge", "Safety Bar Walking Lunge", "QUADS", ["GLUTES"], "BARBELL", []),
    ("goblet_reverse_lunge", "Goblet Reverse Lunge", "QUADS", ["GLUTES"], "KETTLEBELL", []),
    ("single_leg_leg_press", "Single Leg Leg Press", "QUADS", ["GLUTES"], "MACHINE", []),
    ("cable_pull_through_hamstring", "Cable Pull Through", "HAMSTRINGS", ["GLUTES"], "CABLE", []),
    ("single_leg_curl", "Single Leg Leg Curl", "HAMSTRINGS", [], "MACHINE", []),
    ("banded_clamshell", "Banded Clamshell", "GLUTES", [], "RESISTANCE_BAND", []),
    ("smith_machine_hip_thrust_glute", "Smith Machine Hip Thrust", "GLUTES", ["HAMSTRINGS"], "SMITH_MACHINE", []),
    ("seated_calf_raise_machine", "Seated Calf Raise Machine", "CALVES", [], "MACHINE", []),
    ("weighted_crunch", "Weighted Crunch", "CORE", [], "PLATE", []),
    ("cable_woodchop_low_to_high", "Low to High Cable Woodchop", "CORE", [], "CABLE", []),
    ("hanging_toes_to_bar", "Toes to Bar", "CORE", [], "BODYWEIGHT", []),
    ("plate_carries", "Plate Carry", "FULL_BODY", ["CORE", "TRAPS"], "PLATE", []),
    ("suspension_row", "Suspension Row", "BACK", ["BICEPS"], "SUSPENSION", ["TRX Row"]),
    ("suspension_push_up", "Suspension Push Up", "CHEST", ["TRICEPS", "CORE"], "SUSPENSION", ["TRX Push Up"]),
    ("suspension_tricep_extension", "Suspension Tricep Extension", "TRICEPS", [], "SUSPENSION", ["TRX Tricep Extension"]),
    ("suspension_pike", "Suspension Pike", "CORE", ["SHOULDERS"], "SUSPENSION", []),
    ("landmine_rotation_press", "Landmine Rotation Press", "SHOULDERS", ["CORE"], "LANDMINE", []),
    ("landmine_squat_to_press", "Landmine Squat to Press", "FULL_BODY", ["QUADS", "SHOULDERS"], "LANDMINE", []),
    ("single_arm_landmine_row", "Single Arm Landmine Row", "BACK", ["BICEPS"], "LANDMINE", []),
    ("plate_squat", "Plate Squat", "QUADS", ["GLUTES"], "PLATE", []),
    ("plate_lunge", "Plate Lunge", "QUADS", ["GLUTES"], "PLATE", []),
]:
    add(*e)

# Deduplicate by id suffix (later duplicates skipped)
seen_ids = set()
seen_names = set()
unique = []
for ex in EXERCISES:
    if ex[0] in seen_ids:
        continue
    norm_name = ex[1].lower().strip()
    if norm_name in seen_names:
        continue
    seen_ids.add(ex[0])
    seen_names.add(norm_name)
    unique.append(ex)
EXERCISES = unique

print(f"Total exercises: {len(EXERCISES)}")

def fmt_aliases(aliases):
    if not aliases:
        return "emptyList()"
    items = ", ".join(f'"{a}"' for a in aliases)
    return f"listOf({items})"

def fmt_secondary(sec):
    if not sec:
        return "emptyList()"
    return "listOf(" + ", ".join(f"GymMuscleGroup.{s}" for s in sec) + ")"

lines = [
    "package com.deepak.flow.core.gym",
    "",
    "/**",
    f" * Built-in exercise catalogue entries ({len(EXERCISES)} exercises).",
    " * Generated by scripts/generate_exercise_catalog.py - do not edit manually.",
    " */",
    "internal object GymBuiltinExerciseEntries {",
    "",
    "    internal fun all(): List<GymBuiltinExercise> = entries",
    "",
    "    private val entries: List<GymBuiltinExercise> = listOf(",
]

for id_suffix, name, primary, secondary, equipment, aliases in EXERCISES:
    safe_name = name.replace('"', '\\"')
    lines.append(f'        entry("{id_suffix}", "{safe_name}", GymMuscleGroup.{primary}, {fmt_secondary(secondary)}, GymEquipment.{equipment}, {fmt_aliases(aliases)}),')

lines.extend([
    "    )",
    "",
    "    private fun entry(",
    "        idSuffix: String,",
    "        name: String,",
    "        primaryMuscle: GymMuscleGroup,",
    "        secondaryMuscles: List<GymMuscleGroup>,",
    "        equipment: GymEquipment,",
    "        aliases: List<String>,",
    "    ): GymBuiltinExercise = GymBuiltinExercise(",
    '        id = "builtin:$idSuffix",',
    "        canonicalName = name,",
    "        aliases = aliases,",
    "        primaryMuscle = primaryMuscle,",
    "        secondaryMuscles = secondaryMuscles,",
    "        equipment = equipment,",
    "        category = \"Strength\",",
    "    )",
    "}",
    "",
])

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUTPUT}")
